### ISSUE TITLE
The `c-code` mode creates a `.coveragerc`

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#120]
The other modes have moved configuration for `coverage` into `setup.cfg`. The `c-code` mode should do the same.

**Comment by icemac** [comment]
In `pure-python` the configuration for `coverage`  is actually in `tox.ini`.
The basis for the `c-code` template is `zope.interface` which does not use `tox` to run the tests in CI so `tox.ini` does not seem to be the right place.
In `buildout-recipe` we also have a `.coveragerc` because when running `coverage` over multiple processes this is the only way to configure it.

You are right it looks like a mess – but it seems impossible to clean it up in a common way for all templates.

**Comment by dataflake** [comment]
Are you saying putting these settings into `setup.cfg` is not possible for some technical reason? I could understand if that's the case.

**Comment by icemac** [comment]
Yes, the experiments with `setup.cfg` in context of the `buildout-recipe` (which runs processes in parallel and therefore needs special setup to collect the coverage from all the processes) some month ago showed that `coverage` configuration in `setup.cfg` is ignored. This is probably because `setup.cfg` is not accessible/existing in such a setup as it in not really part of the installed distribution.
