### ISSUE TITLE
@odidev: Stop forking foreign repositories into the zopefoundation organization

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#148]
Hi @odidev,

please stop forking foreign repositories into the zopefoundation organization. This is not allowed by our organization policies.

What is your reason behind doing so?

Latest example (there where about 5 examples before):
* `cubefs` (already deleted)

P. S. As you do not provide an email address in your GitHub profile I did not see a way to contact you privately.

**Comment by jugmac00** [comment]
When you have forked a repository already to your personal account, the github UI preselects one of your organizations (maybe the one first in the alphabet?), and if you do not look closely, you fork the repository into the wrong organization.

I assume there is no bad intention behind this.

**Comment by icemac** [comment]
Today I deleted a fork of [rawfile-localpv](https://github.com/zopefoundation/rawfile-localpv).

**Comment by dataflake** [comment]
If you don't hear from him just remove his membership.

**Comment by odidev** [comment]
Hi @icemac Apologies for the delay

Although @jugmac00 deduction is correct and the repositories are getting forked into zopefoundation organization by default as those repositories which got added were already added to my personal account and when I tried to fork it got forked into zopefoundation by default. 

I understand the trouble you have been facing due to this but I assure you there is no bad intention behind this and I will make sure this never happens again. 

Please do let me know if I can help you in any other way.

**Comment by icemac** [comment]
@odidev You could create an organization for yourself. If its name starts with a letter wich is not `z` it should be listed before `zopefoundation` and the duplicate forks will go there.
