### ISSUE TITLE
When to drop Python 2 support?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#15]
The current suggestions seem to be:

* wait until it hurts too much because the tooling (TravisCI etc.) no longer support it
* packages which are the leaves in the dependency tree can be the first ones to drop Python 2 support. (e. g. Zope 5 is dropping Python 2 support)

The reason behind keeping Python 2 support is to ease the migration to Python 3. One could always pin to an older version für Python 2 but the ongoing development in the package could bring some unpleasant surprises for the late adaptor.

Is this a good summary of the current status? Any ideas?

**Comment by jamadden** [comment]
Seems like a good summary [to me](https://github.com/zopefoundation/ExtensionClass/pull/23#issuecomment-602639958).

**Comment by dataflake** [comment]
As a more general comment, some people appear to treat dropping Python 2 support as a goal all by itself, so it gets dropped even when there is no other problem and retaining it wouldn’t cost any effort. That always struck me as short-sighted.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-3-27 08:44 -0700:
>As a more general comment, some people appear to treat dropping Python 2 support as a goal all by itself, so it gets dropped even when there is no other problem and retaining it wouldn’t cost any effort. That always struck me as short-sighted.

I am in favour to not drop Python 2 support quickly. But,
especially tests begin to make problems.

An example is "https://github.com/zopefoundation/Products.ZCatalog"
where the Python 2 tests fail because they want to install
a package in a version which no longer supports Python 2.
I have no idea (yet) how to control versions in the travis
test setup.

**Comment by icemac** [comment]
@d-maurer wrote:
> An example is "https://github.com/zopefoundation/Products.ZCatalog" where the Python 2 tests fail because they want to install a package in a version which no longer supports Python 2.

This one I fixed for you by using the `version.cfg` of Zope 4.x as version pins.
But maybe `Products.ZCatalog` is one of the candidates to drop Python 2 support in near future is it is only used by Zope which has a clear path towards Python 3.

**Comment by dataflake** [comment]
Many Zope products that haven't been updated in a while still reference Zope `master` for their version pins, but all those that still support Python 2 must change that to reference Zope `4.x` since `master` has no Python 2 support anymore.

**Comment by mgedmin** [comment]
If packages declare their supported Python versions with `python_requires` in setup.py, then pip will know to use the last version that supports Python 2.

Unfortunately zc.buildout doesn't use pip.  So you either have to switch Travis configs to use pip instead of zc.buildout (which is what most Zope 3 related packages do), or add manual version pins in the buildout config for every package that drops Python 2 support.

**Comment by mgedmin** [comment]
> Unfortunately zc.buildout doesn't use pip. So you either have to switch Travis configs to use pip instead of zc.buildout (which is what most Zope 3 related packages do), or add manual version pins in the buildout config for every package that drops Python 2 support.

There's a WIP PR for zc.buildout that makes it support python_requires, among other things: https://github.com/buildout/buildout/pull/506

**Comment by jugmac00** [comment]
> Many Zope products that haven't been updated in a while still reference Zope `master` for their version pins, but all those that still support Python 2 must change that to reference Zope `4.x` since `master` has no Python 2 support anymore.

From a quick grep over Zopefoundation's repos, there are only 2 products left to be fixed - I plan to to during today's sprint.

**Comment by dataflake** [comment]
I have packaged the latest state of this discussion into developer guidelines at https://www.zope.org/developer/python2.html. I also moved the wiki page Michael created in this repository onto that page.
