### ISSUE TITLE
Unarchive Products.LongRequestLogger ?

### ISSUE THREAD

**Issue by perrinjerome** [zopefoundation/meta#159]
Hello

In the next few weeks I will probably work on https://github.com/zopefoundation/Products.LongRequestLogger to make it compatible with Zope >=4 WSGIPublisher and python 3.

This tool is very helpful to understand performance issues in production after they happen, I have been using it a lot on Zope2.

Before I start working on that, is there a known tool providing similar functionality that would be recommended instead ? I was thinking that maybe this project is archived because people are using something else - but I could not find out.

Thanks !

/cc @rmonnerat

**Comment by perrinjerome** [comment]
I tried a bit and supporting WSGIPublisher is mostly of adjusting [this monkey patch](https://github.com/zopefoundation/Products.LongRequestLogger/blob/20c0e1994c1b9265587f0ffbd6a63937f197f271/Products/LongRequestLogger/__init__.py#L15-L24) to patch `ZPublisher.WSGIPublisher` instead of `ZPublisher.Publish`, but it might be better (but more work) to implement this using  [`PubStart` event](https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/ZPublisher/pubevents.py#L28) that is emitted [here](https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/ZPublisher/WSGIPublisher.py#L165).

**Comment by d-maurer** [comment]
Jérome Perrin wrote at 2022-9-19 22:31 -0700:
> ...
>Before I start working on that, is there a known tool providing similar functionality that would be recommended instead ?

I am using `haufe.requestmonitor` for this purpose.
It is already adapted for Zope >= 4.

**Comment by ale-rt** [comment]
I am using [slowlog](https://pypi.org/project/) through a custom wsgi.ini, see [this example](https://github.com/euphorie/euphorie-project/blob/dcdbbad658676262ad3a5b7de131c05e7d7a70c7/templates/wsgi.ini#L19).
Anyway [haufe.requestmonitor](https://pypi.org/project/haufe.requestmonitoring) looks more advanced and maintained.

**Comment by perrinjerome** [comment]
Thank you ! all this looks very interesting. I will give this a try. 

One thing that I found useful with `Products.LongRequestLogger` was that it understood `Products.ZMySQLDA` (for reference, [here](https://github.com/zopefoundation/Products.LongRequestLogger/blob/20c0e1994c1b9265587f0ffbd6a63937f197f271/Products/LongRequestLogger/dumper.py#L121-L126)) and when zope was waiting for a mysql query, the sql code of the query was also included in the log. I see haufe.requestmonitoring allows configuring the class used to emit logs directly in `zope.conf`, so it should be possible for me to write a subclass of the [default handler](https://github.com/collective/haufe.requestmonitoring/blob/3e1af58eeeb014a3f94aa3fc37893f68cdbf4dd2/haufe/requestmonitoring/DumpTraceback.py#L64-L85) that would also include the SQL query in the log.

For now, I don't think I'll need to unarchive Products.LongRequestLogger (or maybe just to change the README to recommend [haufe.requestmonitor](https://pypi.org/project/haufe.requestmonitoring) instead).

Thanks again for the pointers.

**Comment by d-maurer** [comment]
Jérome Perrin wrote at 2022-9-20 05:33 -0700:
>One thing that I found useful with `Products.LongRequestLogger` was that it understood `Products.ZMySQLDA` (for reference, [here](https://github.com/zopefoundation/Products.LongRequestLogger/blob/20c0e1994c1b9265587f0ffbd6a63937f197f271/Products/LongRequestLogger/dumper.py#L121-L126)) and when zope was waiting for a mysql query, the sql code of the query was also included in the log. I see haufe.requestmonitoring allows configuring the class used to emit logs directly in `zope.conf`, so it should be possible for me to write a subclass of the [default handler](https://github.com/collective/haufe.requestmonitoring/blob/3e1af58eeeb014a3f94aa3fc37893f68cdbf4dd2/haufe/requestmonitoring/DumpTraceback.py#L64-L85) that would also include the SQL query in the log.

You likley could do that.

However, when I remember right, `haufe.requestmonitor`
uses Zope's extended traceback logging (i.e. the traceback
contains additional information from `__traceback_info__` and
`__traceback_supplement__`.
This would allow you to enhance `ZMySQLDA`, instead, to use
`__traceback_info__` or `__traceback_supplement__` to provide
the SQL information.
In my view, this would be better because it would provide
this information also for the tracebacks in the `error_log` objects.

You could use `dm.zopepatches.logging` to ensure
that Zope's extended traceback logging is used globally.
This would make you independent (in this regard) of the
`haufe.requestmonitor` logging - and give you the extended information
in the logfile for exceptions, too.

**Comment by perrinjerome** [comment]
Thanks again ! that seems a really good idea to use `__traceback_info__`. I'm a bit worried by [this comment](https://github.com/collective/haufe.requestmonitoring/blob/3e1af58eeeb014a3f94aa3fc37893f68cdbf4dd2/haufe/requestmonitoring/DumpTraceback.py#L26-L29) now, I want to chek what happens when a persistent object is referenced in `__traceback_info__`. I'll try all this in the following weeks

**Comment by d-maurer** [comment]
Jérome Perrin wrote at 2022-9-21 19:24 -0700:
>Thanks again ! that seems a really good idea to use `__traceback_info__`. I'm a bit worried by [this comment](https://github.com/collective/haufe.requestmonitoring/blob/3e1af58eeeb014a3f94aa3fc37893f68cdbf4dd2/haufe/requestmonitoring/DumpTraceback.py#L26-L29) now, I want to chek what happens when a persistent object is referenced in `__traceback_info__`. I'll try all this in the following weeks

I have been using the `DumpTraceback` handler for about 15 years.
In this time, I have observed a single crash caused by it.
Thus, the risk is there but it does not seem very high.

As you know, `Zope` is restarted automatically after a crash
in the standard (i.e. `zdaemon` controlled) setup.


Apart from a crash, the handler might raise an exception
if it loads a persistent object from its foreign thread
(a violation of ZODB's main restrictions).

I have not observed such a situation in my use time.
This does not mean that is has not occurred, only that
if it occurred, the effect has not been catastrophic.
