### ISSUE TITLE
c-code template: Wisdom of building manylinux aarch64 wheels

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#167]
Building out the manylinux wheels for aarch64 during the GHA runs takes way too long. For example, while the manylinux wheels for BTrees build in 8-10 minutes for x86_64 and i686 the aarch64 build runs for about 2.5 hours(!). That makes no sense for several reasons. Linux on aarch64 is not a common platform (yet). Those who use it could just as well (and quickly) just download the source distribution and build the egg locally.

**Comment by icemac** [comment]
Part of the problem is, is that the aarch64 wheels are build sequentially by a separate job instead of being built in parallel as the other ones.
I hoped to get this solved by using `cibuildwheel`. But I did not have the time and energy to complete the experiment in https://github.com/zopefoundation/ExtensionClass/pull/39.

**Comment by dataflake** [comment]
I'll just rely on the configurations stabilizing again, this only became an issue when I had to go through many C packages at once several times.
