### ISSUE TITLE
The time to drop Python 2 support is now!

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#177]
The maintenance burden becomes heavier every week:

* some weeks ago GHA's `ubuntu-latest` no longer contains Python 2.7 up to 3.6, so each repository has to be updated (we are still far away from that update to be complete)
* tox 4 no longer supports the negation syntax used to exclude older python versions from certain actions, see #176
* @vstinner archived `faulthandler` and deleted it from PyPI – we used it for our packages containing C code, to these builds are now also broken, see https://github.com/zopefoundation/BTrees/pull/188 where I try to run without it

We could work around all these issues and the ones to strike in future. But the time it takes, we could perfectly use in other places.
For me the only way to actually make progress is to run https://zope.dev/developer/python2.html#how-to-drop-support on all our repositories before even more problems arise.

I volunteer to rip out Python 2.7 up to 3.6 support form zopefoundation repositories. Even though I know this will take weeks, but fixing the current problems will also take weeks to get GHA green again.

@dataflake @mgedmin @jamadden @d-maurer Any ideas?

**Comment by dataflake** [comment]
Ah, that explains the one failure I saw about `faulthandler`. It boggles my mind why people would just delete releases and willingly break an unknown number of other projects.

In the new release schedule at https://www.zope.dev/releases.html I had already declared Zope 4 as End of Life on 12/31, and Zope 4 was the only reason we have kept Python 2 support going. I am **very** happy to see that support burden go away.

You're right, now is a good time to make the cut. I'm not sure about Python 3.6, though - does it take extra effort or workarounds to keep that in?

**Comment by mauritsvanrees** [comment]
Plone 6.0 requires 3.8+ already.

Python 3.7 is only supported for half a year still, so Zope packages could consider to drop this as well. That version will likely start to give similar problems after a while.

**Comment by dataflake** [comment]
I just remembered that a missing Python 3.6 on `ubuntu-latest` was the reason for the recent test matrix changes, so the question is answered - workarounds are required for Python 3.6 support.

I would suggest that after merging https://github.com/zopefoundation/Zope/pull/1081 I also remove Python 3.6 there and release it as 5.8. We had announced dropping that a while ago, so that feels safe.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2022-12-19 00:14 -0800:
> ...
>@dataflake @mgedmin @jamadden @d-maurer Any ideas?

I am fine with dropping Python 2 support.

I would prefer if packages could still be built and installed from
source (i.e. no binary wheel support) in older Python versions
(e.g. 2.7, 3.5, 3.6) -- without official support for those versions.

**Comment by dataflake** [comment]
> I am fine with dropping Python 2 support. I would prefer if packages could still be built and installed from source (i.e. no binary wheel support) in older Python versions (e.g. 2.7, 3.5, 3.6) -- without official support for those versions.

Source tarballs will still be published. But you'd have to download them manually. Once support is no longer declared in the package metadata tools like pip will refuse to install it.

**Comment by mauritsvanrees** [comment]
> Once support is no longer declared in the package metadata tools like pip will refuse to install it.

Older pip versions (or maybe this is in setuptools) ignore `python_requires` in the metadata and will happily install such versions. I don't know which maximum pip/setuptools versions you could use though.
Buildout 2 also ignores this info.

**Comment by mgedmin** [comment]
:+1: for dropping 2.7 and 3.6.

**Comment by dataflake** [comment]
Take a look at https://github.com/zopefoundation/Zope/pull/1083 which drops Python 3.6 support for Zope `master` / 5

**Comment by mauritsvanrees** [comment]
@dataflake The changes in your PR for dropping 3.6 seem good. But I would hope that you do this *after* another 5.7.x release with the latest fix for regressions after the security fix. Otherwise it feels a bit like `waitress`, where they said: "All versions have a security bug, we have only fixed it in a version that requires 3.7+." Understandable and defendable, but not too nice.
The tests currently still pass on Zope master, right?

From a Plone standpoint it does not matter though.

**Comment by dataflake** [comment]
The problem is that we do not know how many more releases are required to find all issues caused by the change in default content type in the publisher. Those who really still use Zope 5 on Python 3.6 and not Plone won't be any safer with a separate 5.7.3 release. So instead of spending the time on two releases I would much rather make it one.

**Comment by dataflake** [comment]
I have released 5.7.3 from master after all. Apparently there is now yet another issue installing on macOS on GHA with Python 3.9 and 3.10 and I chose to ignore that for the moment.

**Comment by dataflake** [comment]
@icemac I believe this issue can be closed because we have agreed on the way forward, correct?

**Comment by icemac** [comment]
It's not yet done but we are on the way dropping support for sunsetted Python versions.
