### ISSUE TITLE
Zope Organization at PyPI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#199]
PyPI announced the introduction of organisations, see https://blog.pypi.org/posts/2023-04-23-introducing-pypi-organizations.

I applied for a `zope` organisation as suggested by the Plone Steering Circle.
When the organisation is actually created, we can decide whether we want to use it. I just registered the name. I hope the organisations feature can help to shape the list of people who can cut releases.

**Comment by dataflake** [comment]
If such an organization allows managing users who can make releases that filter down to the individual projects that would be great. No more begging for access to older projects.

**Comment by icemac** [comment]
@dataflake The `zope` organization got created, I sent you an invite as `admin`. See https://pypi.org/manage/organization/zope/people/ for the existing roles. I think we still have to add projects to that organization, so begging for access to older projects will not be solved by this organization but it could allow to give only people release rights who are still active in the projects and allow a central management of those people.

**Comment by icemac** [comment]
As an example I moved `Zope` to the organization, see https://pypi.org/org/zope/ and https://pypi.org/project/Zope/ (left column under owner).

**Comment by dataflake** [comment]
OK, so the move only changes one thing on the project itself, the person doing the move is taken off the individual project's collaborator list. So it's safe to do the move at any time, it won't change anyone's workflow or privileges.

There's apparently no intelligence to check if other individual contributors exist/have the same rights at the organization level. "Cleanup" still needs to be done manually.

I personally like the fact that now we have one single place on PyPI that lists all projects under the organization.

How do you want to proceed? I haven't looked if the organization stuff is already part of the API and I could cobble together a script.

**Comment by dataflake** [comment]
P.S.: I am confusing PyPI and GitHub regarding the API, sorry. This may be a manual process after all.

**Comment by icemac** [comment]
I think we have to come up with a plan how we will handle the PyPI organisation, maybe we meet sometime in the next months to talk about it.

**Comment by dataflake** [comment]
IMHO using it is a safe thing to do that won't really change anything for any project, other than removing the person who does the move from the project-local list of collaborators. Since the project will then include organization-level admins automatically it won't change anything in practice. So if we just move the projects and do nothing else we simply gain better visibility and order by being able to point to a single listing page for ZF projects, and by having a visible marker on projects' pages about that organization membership. I see no loss, even if we don't do anything after the basic move, just small gains and - for the future - easy administration of organization-wide privileges.

Zope Sprint time..?

**Comment by dataflake** [comment]
I suggest we proceed by moving packages into the organization bit by bit as you or I have time. As I said before, this is a safe change and offers the benefit of better visibility under a single umbrella and centralized privilege management for adding new release managers.

**Comment by dataflake** [comment]
I have now moved all ZF projects that I have access to (log into PyPI and visit https://pypi.org/manage/projects/) to the Zope organization.

**Comment by tseaver** [comment]
@dataflake Nice work!  I did see a huge raft of notifications from PyPI about the changes.

**Comment by icemac** [comment]
Hopefully the many mails inspire former developers to remove themselves from being owners of packages they no longer use, see also #233.

@dataflake Thank you for doing the migration. Is there something left to do, or can we close this issue as completed?

**Comment by dataflake** [comment]
@icemac I don't think anyone will actually remove themselves. We would have to do this.

There are literally hundreds of ZF packages left where I don't have PyPI access to do this migration. The issue should remain open as a reminder. Have you visited https://pypi.org/manage/projects/ to find unmigrated packages where you have access but I do not?

**Comment by dataflake** [comment]
- visit the project's PyPI page
- click on Manage Project
- click on Settings
- the section for adding to an organization is on that page. 

It will make you select the organization (you must be a member) and then type the project name to continue.

**Comment by tseaver** [comment]
I've made that transfer for all the non-organization projects in the `zope` namespace for which I had `owner` role.

I also *removed* myself (wrongly) from having the role on the `Zope` and `zope.interface` projects:  I'd prefer to still be able to see those settings, either by having somebody re-add them or by being an `owner` rather than `maintainer` for the organization.

I did *not* touch projects in the `zc.*` namespace:  at least some of them were related to buildout, which has its own Github org (but likely not a PyPI org yet).  @jimfulton might know enough to parse them out.

**Comment by dataflake** [comment]
I'll make you an owner on the organization, no problem

**Comment by tseaver** [comment]
@dataflake TYVM.

**Comment by icemac** [comment]
I just moved all the zopefoundation projects I have owner access to the PyPI organization.

**Comment by icemac** [comment]
I think we are now done with this issue, right?

**Comment by dataflake** [comment]
I would guess any remaining projects that are in the GitHub zopefoundation organization but not in the PyPI zope organization aren't that important and we can "clean it up" when we notice them.
