### ISSUE TITLE
Flake8/PEP-8 checks for PRs

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#3]
See https://pep8speaks.com which provides a GitHub app to automatically check PRs for Flake8 violations.

Pros:

* Improved visibility of Flake8 violations in the PR (better than running a Flake8 job via TravisCI which only makes TravisCI red without telling that only Flake8 is violated)

Cons:

* Each repository needs a special config yaml file.

**Comment by dataflake** [comment]
IMHO a much better idea than a completely failing a Travis CI job. Travis CI should only fail if there are real issues.

**Comment by mgedmin** [comment]
pep8speaks looks very interesting!   It will look even more appealing if they implement [support for GitHub Checks API](https://github.com/OrkoHunter/pep8speaks/issues/89) instead of spamming PRs with comments like coveralls used to do.

> Each repository needs a special config yaml file.

https://github.com/OrkoHunter/pep8speaks/#configuration says "**A config file is not required for the integration to work.**"

OTOH I don't know if the defaults are fine for ZF repos (e.g. apparently it uses pycodestyle instead of flake8 by default).

I wonder if we could submit an upstream PR to default to flake8 when it finds a `flake8` section in setup.cfg?

**Comment by jugmac00** [comment]
For my own and my companies projects I use `pre-commit`, ie the commit fails when there are flake8 issues. So there is no big chance that only CI detects flake8 violations. But certainly, CI also does flake8 checks - via tox. And to complete the loop, one could trigger `pre-commit` from tox.

=> no external GitHub app dependencies
=> no more "please flake8" commits

**Comment by icemac** [comment]
We are adding tox environments to lint the code using  https://github.com/zopefoundation/meta/blob/master/config/config-package.py.
So this issue will be solved over time as more packages are switched to the new template.
