### ISSUE TITLE
Travis-ci.org shuts down Dec 31st

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#36]
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by dataflake** [comment]
FYI, I have done this migration manually for DocumentTemplate because travis-ci.org seemed stuck for that. All I needed to do as this:

- log into travis-ci.com (it uses GitHub for logins)
- click on my account symbol at the top right and go to Settings
- select the zopefoundation organization from the list of organizations on the left
- select the Migrate link on the main page
- use the search field to find the repository
- select the desired repositories from the list and click the Migrate button

I also visited the Settings | Webhooks page in the DocumentTemplate repository and deleted the old webhook that points to travis-ci.com. That's all I had to do.

On travis-ci.com it is possible to select many repositories to move at once, so this should be a quick procedure. This does not remove old webhooks, though. You need to visit the repositories and remove them manually or with some script.

**Comment by icemac** [comment]
I believe the old web hooks are already not used any more as we installed the TravisCI GitHub App for the whole zopefoundation organization. Deleting them does not hurt either.

**Comment by icemac** [comment]
I started migrating all zopefoundation projects to travis-ci.com. It is a bit longer process as you can only convert about 20 projects in a batch.

**Comment by icemac** [comment]
Okay, it was easier than I thought, https://travis-ci.com/organizations/zopefoundation/migrate is now empty aka each package is migrated to travis-ci.com.

We'll see the consequences, but for now I am closing this issue.

**Comment by dataflake** [comment]
Great, thanks for handling that. Let's hope all those old web hooks won't cause issues.

**Comment by mgedmin** [comment]
Do Travis badge URLs need to be updated in all the READMEs?

Do I need to update the script that generates https://zope3.pov.lt/py3/travis.html?

**Comment by dataflake** [comment]
Anything that points to host names ending in travis-ci.org will probably need changing. Thank you for that reminder, I didn't have that on my radar.

**Comment by dataflake** [comment]
P.S.: I just did a manual check and it seems just replacing `.org` with `.com` for the badge URL appears to work. @jugmac00 I see you're working on a organization-wide change already, can you add that as well?

**Comment by jugmac00** [comment]
Sure thing!

**Comment by dataflake** [comment]
All those 3.9-related PRs are now done. Since I had to visit all of those repositories I also deleted the old web hook.

One thing I noticed are branch protection rules that point to Travis CI under a name that no longer works. Visiting Settings | Branches and editing the branch protection rule fixes that.

**Comment by jugmac00** [comment]
![Screenshot from 2020-10-28 14-46-38](https://user-images.githubusercontent.com/9895620/97444407-66ddcf00-192c-11eb-8c70-cf29adc81b99.png)

**Comment by dataflake** [comment]
I visited every single one of those Travis PRs, merged them, deleted the travis-ci.org webhook and checked for branch protection rules that would fail because they referred to Travis the wrong way. I think this is now done.

**Comment by jugmac00** [comment]
Thanks for your time!

**Comment by icemac** [comment]
Thank you all for your great time investment. Is there still something open or can this issue get closed now?

**Comment by jugmac00** [comment]
I think it is all done. If there is anything left, just re-open the issue.
