### ISSUE TITLE
How to start tests?

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/meta#92]
After I created "https://github.com/zopefoundation/ZEO/pull/174", the tests have been executed (and failed because of a test problem). Unfortunately, no tests run after I fixed the error. How can I start those tests?

**Comment by dataflake** [comment]
No one can start those tests right now. Our allowed runtime on Travis CI has expired, once again. This is due to their change of business model, open source projects used to have unlimited runtime on Travis CI. Now they only have a limited time.

We are in the process of moving all projects away from Travis CI to GitHub Actions. There is no fixed timeline for this. Some repositories are easy to move, some aren't. Until then you should rely on the local `tox` configuration and run tests locally.
